# Generated by Django 3.2.24 on 2024-03-02 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='menu_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.food_menu'),
            preserve_default=False,
        ),
    ]
