# Generated by Django 3.2.24 on 2024-03-03 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_payment_menu_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food_menu',
            name='login',
        ),
    ]
